services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: f1-goat-backend
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - f1-network

  frontend:
    build:
      context: front
      dockerfile: Dockerfile
    container_name: f1-goat-frontend
    volumes:
      - frontend-static:/static
    networks:
      - f1-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: f1-goat-nginx
    ports:
      - "80:80"
    volumes:
      - frontend-static:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - f1-network

volumes:
  frontend-static:

networks:
  f1-network:
    name: f1-goat-network
