config:
  validation: true

style:
  active: true

  UnusedPrivateProperty:
    active: true

  ForbiddenComment:
    active: true

  MagicNumber:
    active: true
    ignoreNumbers: [ '-1', '0', '1', '2' ]
    excludes: [ '**/test/**', '**/*Test.kt', '**/*Tests.kt', '**/*Spec.kt' ]

  ReturnCount:
    active: true
    max: 3
    excludeGuardClauses: true

  SerialVersionUIDInSerializableClass:
    active: false

naming:
  active: true

  FunctionNaming:
    active: true
    excludes: [ '**/test/**', '**/*Test.kt', '**/*Spec.kt' ]

potential-bugs:
  active: true

  LateinitUsage:
    active: true

complexity:
  active: true

  TooManyFunctions:
    active: true
    allowedFunctionsPerFile: 30
    allowedFunctionsPerClass: 30
    allowedFunctionsPerInterface: 20
    excludes: [ '**/test/**', '**/*Test.kt', '**/*Spec.kt' ]

  LongMethod:
    active: true
    allowedLines: 100
    excludes: [ '**/test/**', '**/*Test.kt' ]

  LargeClass:
    active: true
    allowedLines: 1000
    excludes: [ '**/test/**', '**/*Test.kt' ]

  LongParameterList:
    active: true
    allowedFunctionParameters: 8
    allowedConstructorParameters: 10
    ignoreDefaultParameters: true

ktlint:
  active: true
  android: false
  autoCorrect: true

  MaximumLineLength:
    maxLineLength: 120

  ImportOrdering:
    active: true

  NoWildcardImports:
    active: true

  TrailingCommaOnDeclarationSite:
    active: true

  TrailingCommaOnCallSite:
    active: true
