[versions]

# Core
java = "21"
kotlin = "2.3.0"
spring-boot = "4.0.1"

# Utils
detekt = "1.23.8"

#-----------------------------------------------------------------------------------------------------------------------

[libraries]

# Spring Boot starters
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

# Kotlin
jetbrains-kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

#-----------------------------------------------------------------------------------------------------------------------

[plugins]

# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

# Spring
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

# Detekt
detekt-plugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
